name: dart_transmission_rpc
description: |
  A Transmission RPC client implemented in Dart, supporting RPC version>=14.
version: 0.1.1
homepage: https://github.com/FriesI23/dart_transmission_rpc
repository: https://github.com/FriesI23/dart_transmission_rpc
issue_tracker: https://github.com/FriesI23/dart_transmission_rpc/issues
# documentation:

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.7.2
  mockito: ^5.4.4
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
funding:
  - https://www.buymeacoffee.com/d49cb87qgww

topics:
  - transmission
  - rpc
